### ISSUE TITLE
How do we get a string representation?

### ISSUE THREAD

**Issue by trusktr** [exos/node-randbytes#2]
`console.log(buff);` shows `<buffer ...>` but I'd like to get the string representation (utf-8 preferably?) of the random bytes.

How would I get that?

**Comment by exos** [comment]
random bytes returns a Buffer object: 
http://nodejs.org/api/buffer.html

Binary blocks should not be represented as unicode strings (like utf-8), you can do this using `console.log(buff.toString('utf-8'));`, but if you need to save it in plain text format or obtain a human like result, I recommend you use hex or base64 encodings:

``` javascript
RandBytes.getRandomBytes(32, function (buf) {
 console.log('Bas64:', buf.toString('base64'));
 console.log('HEX:', buf.toString('hex'));
 console.log('UTF-8:', buf.toString('utf-8'));
 console.log('Binary:', buf.toString('binary'));
 console.log('ASCII:', buf.toString('ascii'));
});
```

This show:

```
Bas64: KQSBaABZ9ZJ7yKDz/dsOgufnJnf6McP91zkObjbNdwM=
HEX: 290481680059f5927bc8a0f3fddb0e82e7e72677fa31c3fdd7390e6e36cd7703
UTF-8: )�hY��{Ƞ������&w�1���9n6�w
Binary: )hYõ{È óýÛçç&wú1Ãý×9n6Íw
ASCII: )hYu{H s}[gg&wz1C}W9n6Mw
```

All node.js API modules use Buffer objects to manage data chunks, you can send this result without convert to as string.

ie: 

``` javascript
RandBytes.getRandomBytes(32, function (buf) {
    fs.writeFile('data.bin', buf, function (err) {
         if (!err) console.log("data saved!");
    });
});
```

**Comment by trusktr** [comment]
Thank you, that was very helpful!
